"""Add document_source_id column to Document

Revision ID: 8d7fa037fcd1
Revises: bcb54358344f
Create Date: 2025-03-27 01:52:49.207264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d7fa037fcd1'
down_revision: Union[str, None] = 'bcb54358344f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_source_id', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus'),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_unique_constraint(None, 'documents', ['document_source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus'),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'document_source_id')
    # ### end Alembic commands ###
